### ISSUE TITLE
Update SYSTEM_IDS

### ISSUE THREAD

**Issue by Koloss0** [UMSATS/soti#20]
The [NodeID](https://github.com/UMSATS/tsat-utilities-kit/blob/e6e9c9386bd9c61bc6a9d05f250f76c9c4067730/Inc/tuk/can_wrapper/can_message.h#L19-L25) enum in TUK doesn't correlate with [SOTI's SYSTEM_IDS dictionary](https://github.com/UMSATS/soti/blob/58782df73e915946829c4c7ae2fef346b9720e06/soti-cli/cli_utils/constants.py#L78C1-L84C2).

Todo:
- [ ] Update the dictionary to match **exactly** the contents of `NodeID`. There should be no discrepancy in the values or names.
- [ ] Rename `SYSTEM_IDS` to `NodeID` and make it an [enum](https://www.geeksforgeeks.org/enum-in-python/).

_Originally posted by @Koloss0 in https://github.com/UMSATS/soti/issues/13#issuecomment-2313320165_

**Comment by ArnavG-it** [comment]
Can I add the related feature you mentioned [here](https://github.com/UMSATS/soti/issues/13#issuecomment-2308014336) to this issue? I'm mostly done with it.
