### ISSUE TITLE
Implement new send command syntax

### ISSUE THREAD

**Issue by Koloss0** [UMSATS/soti#25]
The current `send` command is very limited. It only lets you send a command code to a pre-defined target recipient. That's only a sliver of the functionality we actually want.

Recall that a message has several different properties:
- The sender ID: Who is sending the message.
- The recipient ID: Who is the target recipient.
- Priority: Used in arbitration. Lower values are higher priority.
- Command code: The command that's being issued.
- Message body: Extra payload data if applicable for the issued command. (max 7 bytes)
- Acknowledgement Flag: Indicates whether the message is simply echoing a previous message for the purposes of acknowledging its receipt.

Some notes about these:
- The sender ID and recipient ID can be one of CDH, PWR, ADCS, and PLD.
- the command code will be one of the 45 possible values.

The new send command should make it possible (and ideally easy) to configure all of these properties, so that testers have complete control over the messages they are transmitting.

**New Syntax:**

```
send <recipient> <command> [data] [options]
```

**Examples:**

```
send PWR PWR_SET_SUBSYSTEM_POWER 0x03 0x01
send PLD PLD_TEST_LEDS from=CDH
send ADCS ADCS_GET_MAGNETORQUER_DIRECTION from=CDH priority=0
send PLD 0x23 ack=true
```

Note that both command names and command codes should be valid for the command argument.

To reduce typing, the `from=` option can be omitted and will default to the value from the most recent `setid` command. By the way, perhaps it's time to give it a better name. How about `iamnow`? (no I'm serious- 🤨)

```
iamnow CDH
send PLD PLD_TEST_LEDS
```

Let me know if you have any questions or suggestions.

**Comment by Koloss0** [comment]
As a bonus, you should also delete the `dest` field from `COMM_INFO` and just make use of the user-defined sender IDs. This will have the side-effect of fixing the crash that occurs when trying to send a command with `None` for the target recipient.

**Comment by ArnavG-it** [comment]
Good write-up. Do you think the non-common commands should have a default recipient (like the current `dest`), or should it always be specified by the user?

I was trying to fit the verb theme with `setid` but `iamnow` is good, especially when the recipient is variable as well.

**Comment by Koloss0** [comment]
Yeah, the issue with `setid` is there's two ID's involved (three if you consider the command ID). You could also have `set-sender` and that would be logical, but `iamnow` is shorter and more fun.

Good question. Actually, keeping the default destinations for the non-common commands could be useful in reducing typing for the vast majority of situations. It's quite rare that you would want to send ADCS commands to Power after all. So, yeah I think we should keep the `dest` fields. So maybe the syntax can just be:

```
send <command> [data] [options]
```

And you can specify `to=` as an option. For common commands it would be required or else you get a warning.

**Comment by ArnavG-it** [comment]
I think [argparse](https://docs.python.org/3/library/argparse.html) would be the simplest approach for this, unless there's objections. The syntax would have to be more like this:
```
send PWR_SET_SUBSYSTEM_POWER --data 0x03 0x01 --from CDH
```

**Comment by Koloss0** [comment]
We could, but it's pretty easy to make our own parser with `.split()`. Here's a good start:

```python
def parse_send(args: str):
    parts = args.split()

    cmd_id = parse_cmd_id(parts[0])
    data = []
    options = {}

    # Parse remaining parts
    has_data: Bool = False
    for index, part in enumerate(parts[1:]):
        if index == 1 and not "=" in part: # Detect if the data argument is provided.
            has_data = True
        
        if '=' in part:  # Check if key-value pair.
            key, value = part.split('=')
            options[key] = value
        elif has_data:  # Data
            data.append(part)
        else: # Invalid.
            raise SyntaxError(f"Unknown argument '{part}'")
    
    # Now data and options are parsed. Just need to process it.
    return {"cmd": cmd_id, "data": data, "options": options}
```

**Comment by ArnavG-it** [comment]
Sounds good, I'll try getting that syntax working. Thanks for starting on it.

If you want to check it out, I did the argparse version on [this branch](https://github.com/UMSATS/soti/tree/feat/send-arguments), which seems to be working (but only accepts command names and doesn't handle bad input).

**Comment by ArnavG-it** [comment]
I haven't implemented the `is_ack` flag yet, I'm assuming that is dependent on #24? If so, I'd rather just leave that out of this issue for now.

We can go over it next meeting, but if you're curious I did open the PR (#28) to compare the changes @Koloss0.

**Comment by Koloss0** [comment]
Yep, we can leave it for #24. I took a look and your changes look very good. Nice job!
