### ISSUE TITLE
Listener thread doing too much work

### ISSUE THREAD

**Issue by ArnavG-it** [UMSATS/soti#6]
Problem: At the moment, the thread that listens for new messages also parses the message and saves it to a file. This leads to messages being lost due to the thread being overworked when lots of messages come in at once.

Proposed Fix: The thread should be split into 2 separate threads. One thread only listens for new messages and puts them into a big queue. The other thread receives the message from this queue, then does the parsing and storing to a file.

**Comment by GrahamDrive** [comment]
Going to close this and just have this task under the [debugging task for soti ](https://github.com/UMSATS/soti/issues/2).
